# -*- mode: ruby -*-
# vi: set ft=ruby :

WAN_IP = "192.168.56.2"

UE_IP = "192.168.56.100"
UE_LAN_IP = "192.168.60.2"

HOST1_IP = "192.168.60.100"
HOST2_IP = "192.168.60.200"

$wan_install = <<-'SCRIPT'

sudo ip link add link enp0s8 name enp0s8.1 type vlan id 1
sudo ip addr add 10.46.0.1/24 dev enp0s8.1
sudo ip link set enp0s8.1 up

sudo ip link add link enp0s8 name enp0s8.2 type vlan id 2
sudo ip addr add 10.46.0.2/24 dev enp0s8.2
sudo ip link set enp0s8.2 up

echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
sudo sysctl -w net.ipv4.ip_forward=1

SCRIPT

$ue_install = <<-'SCRIPT'

sudo ip link add link enp0s8 name enp0s8.1 type vlan id 1
sudo ip addr add 10.46.0.100/24 dev enp0s8.1
sudo ip link set enp0s8.1 up

sudo ip link add link enp0s8 name enp0s8.2 type vlan id 2
sudo ip addr add 10.46.0.200/24 dev enp0s8.2
sudo ip link set enp0s8.2 up

echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
sudo sysctl -w net.ipv4.ip_forward=1

echo "101 vlan1" | sudo tee -a /etc/iproute2/rt_tables
echo "102 vlan2" | sudo tee -a /etc/iproute2/rt_tables

# For 192.168.60.100 -> Route via enp0s8.1
sudo ip rule add from 192.168.60.100 lookup vlan1
sudo ip route add default via 10.46.0.1 dev enp0s8.1 table vlan1

# For 192.168.60.200 -> Route via enp0s8.2
sudo ip rule add from 192.168.60.200 lookup vlan2
sudo ip route add default via 10.46.0.2 dev enp0s8.2 table vlan2

SCRIPT

$host_install = <<-'SCRIPT'

sudo ip route add default via 192.168.60.2 dev enp0s8

SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "wan" do |wan|
    wan.vm.box = "ubuntu/jammy64"

    wan.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    wan.vm.hostname = "wan"
    wan.vm.network "private_network", ip: WAN_IP

    # Interface configuration
    wan.vm.provision "shell", inline: $wan_install
  end

  config.vm.define "ue" do |ue|
    ue.vm.box = "ubuntu/jammy64"

    ue.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    ue.vm.hostname = "ue"
    
    # WAN interface
    ue.vm.network "private_network", ip: UE_IP

    # LAN interface
    ue.vm.network "private_network", ip: UE_LAN_IP

    # Interface and Route configuration
    ue.vm.provision "shell", inline: $ue_install
  end

  config.vm.define "host1" do |host1|
    host1.vm.box = "ubuntu/jammy64"

    host1.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    host1.vm.hostname = "host1"
    host1.vm.network "private_network", ip: HOST1_IP

    # Interface and Route configuration
    host1.vm.provision "shell", inline: $host_install
  end

  config.vm.define "host2" do |host2|
    host2.vm.box = "ubuntu/jammy64"

    host2.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    host2.vm.hostname = "host2"
    host2.vm.network "private_network", ip: HOST2_IP

    # Interface and Route configuration
    host2.vm.provision "shell", inline: $host_install
  end
end
