#!/bin/bash

CERT_CLIENT_PASSWD=$1
NAUN3_IP=$2

sudo apt update

sudo apt-get update
sudo apt-get -y install wpasupplicant

echo -e "\nRemove IP address"
sudo ip addr del $NAUN3_IP/24 dev enp0s8

echo -e "\nWriting wpa_supplicant configurations"
echo -e 'ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=vagrant
eapol_version=2
ap_scan=0

network={
    eapol_flags=0

    key_mgmt=IEEE8021X
    eap=TLS

    identity="user@example.org"
    ca_cert="/certs/ca.pem"
    private_key="/certs/client.p12"
    private_key_passwd="'$CERT_CLIENT_PASSWD'"
}' > wpa_supplicant.conf

LOG_FILE_PATH="/log/$(cat /etc/hostname)_wpa_supplicant_$(date +%s).log"
cat wpa_supplicant.conf > ${LOG_FILE_PATH}

echo -e "\nRunning wpa_supplicant"
sudo wpa_supplicant -tKdd -ienp0s8 -Dwired -c./wpa_supplicant.conf &>> ${LOG_FILE_PATH} &

sleep 15

sudo dhclient enp0s8

sleep 30

sudo killall wpa_supplicant
sudo killall dhclient

sleep 5

echo -e "\nwpa_supplicant and dhclient killed"