#!/bin/bash

sudo apt update

sudo apt-get update
sudo apt-get -y install wpasupplicant

echo -e "\nRemove IP address"
sudo ip addr del $2/24 dev enp0s8

echo -e "\nWriting wpa_supplicant configurations"
echo -e 'ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=vagrant
eapol_version=2
ap_scan=0

network={
    eapol_flags=0

    key_mgmt=IEEE8021X
    eap=TLS

    identity="user@example.org"
    ca_cert="/certs/ca.pem"
    private_key="/certs/client.p12"
    private_key_passwd="'$1'"
}' > wpa_supplicant.conf

LOG_FILE_PATH="/log/wpa_supplicant_$(date +%s).log"
cat wpa_supplicant.conf > ${LOG_FILE_PATH}

echo -e "\nRunning wpa_supplicant"
sudo wpa_supplicant -tKdd -ienp0s8 -Dwired -c./wpa_supplicant.conf &>> ${LOG_FILE_PATH} &